% Please execute this code section wise
% so that the values of the variables
% settle and are stable
%

clc; clear ; close all;
% 
%% Elliptic Lowpass filter transfer function and plots
[z, p, H0, B, A] = ellipap2(3, 1.411, 16.48);
syms sl Omega_L;
H_LPF = (B(1,1)+B(1,2)*sl+sl^2*B(1,3))*(B(2,1)+B(2,2)*sl+sl^2*B(2,3))/((A(1,1)+A(1,2)*sl+sl^2*A(1,3))*(A(2,1)+A(2,2)*sl+sl^2*A(2,3)));
H_LPF_freq = subs(H_LPF, sl, 1i * Omega_L);
[ns, ds] = numden(H_LPF);
nsl = sym2poly(ns);
dsl = sym2poly(ds);
k = ds(1);
ns = ns / k;
ds = ds / k;
disp(nsl);
disp(dsl);
figure();
fplot(abs(H_LPF_freq));
hold on;
fplot(sl - sl - 0.15 + 1, 'k-', 'Markersize', 10);
hold on;
fplot(sl-sl+1, 'k-', 'Markersize', 10);
hold on;
fplot(sl - sl + 0.15, 'r-', 'Markersize', 10);
xline(1, 'magenta-');
hold on;
xline(1.2488,'magenta-');
axis([0 2 0 1.2]);
set(gca, 'XTick', [0, 1, 1.2488], 'xticklabel', {'0', '\Omega_{Lp} = 1','\Omega_{Ls} = 1.2488'});
set(gca, 'YTick', [0.15, 0.85, 1], 'yticklabel', {'\delta_2 = 0.15', '1 - \delta_1 = 0.85', '1'});
daspect([1 1 1]);
title('Equivalent Elliptic Lowpass filter mangitude response');
xlabel('\Omega_L');
ylabel('|H(j \Omega_L)|');
 figure();
 fplot(angle(H_LPF_freq));
 xlabel('\Omega_L');
 ylabel('\angle H(j \Omega_L)');
 title('Equivalent Elliptic Lowpass filter phase response');
%% Analog lowpass to bandstop frequency transformation
syms s Omega;
B = 0.5009;
Omega_0 = 1.0081;
H_BSF = subs(H_LPF, sl, (B * s) / (s^2 + Omega_0^2) );
[ns, ds] = numden(H_BSF);
ns = sym2poly(ns);
ds = sym2poly(ds);
k = ds(1);
ns = ns / k;
ds = ds / k;
disp(ns);
disp(ds);
H_BSF_freq = subs(H_BSF, s, 1i * Omega);
figure();
fplot(abs(H_BSF_freq));
set(gca, 'XTick', [0.7883, 0.8273, 1.2283, 1.2892], 'xticklabel', {'\Omega_{p1}', '\Omega_{s1}', '\Omega_{s2}', '\Omega_{p2}'});
set(gca, 'YTick', [0.15, 0.85, 1], 'yticklabel', {'\delta_2 = 0.15', '1 - \delta_1 = 0.85', '1'});
hold on;
xline(0.7883, 'magenta-');hold on;
xline(0.8273, 'magenta-');hold on;
xline(1.2283, 'magenta-');hold on;
xline(1.2892, 'magenta-');
hold on;
fplot(s - s - 0.15 + 1, 'k-', 'Markersize', 10);
hold on;
fplot(s-s+1, 'k-', 'Markersize', 10);
hold on;
fplot(s -s + 0.15, 'r-', 'Markersize', 10);
daspect([1 1 1]);
title('Elliptic Bandstop filter mangitude response');
xlabel('\Omega');
ylabel('|H(j \Omega)|');
axis([0 2 0 1.2]);
figure();
 fplot(angle(H_BSF_freq));
 xlabel('\Omega');
 ylabel('\angle H(j \Omega)');
 title('Elliptic Bandstop filter phase response');
%% Analog to z bilinear transformation
syms z;
Hz = subs(H_BSF, s, (z-1)/(z+1));
[Nz, Dz] = numden(Hz);
Nz = sym2poly(Nz);
Dz = sym2poly(Dz);
k = Dz(1);
Nz = Nz / k;
Dz = Dz / k;
disp(Nz);
disp(Dz);
[H,f] = freqz(Nz,Dz,1024*1024, 400e3);
plot(f,abs(H));
axis([0 150e3 0 1.3]);
hold on;
yline(1, 'red--', 'LineWidth', 1.5);
hold on;
yline(0.85, 'red--', 'LineWidth', 1.5);
hold on;
yline(0.15, 'red--', 'LineWidth', 1.5);
hold on;
xline(88e3, 'magenta--', 'LineWidth', 1.5);
hold on;
xline(113e3, 'magenta--', 'LineWidth', 1.5);
xlabel('f in 10^4 Hz');
ylabel('|H(e^{j 2\pi f})|');
title('Magnitude Response of the Discrete Time Bandstop Filter');
set(gca, 'XTick', [85e3, 88e3, 113e3, 116e3], 'xticklabel', {'f_{p1}', 'f_{s1}', 'f_{s2}', 'f_{p2}'});
set(gca, 'YTick', [0.15, 0.85, 1, 1.15], 'yticklabel', {'\delta_2 = 0.15', '1 - \delta_1 = 0.85', '1', '1 + \delta_1 = 1.15'});
fvtool(Nz, Dz, 'Analysis', 'Phase');